### ISSUE TITLE
Add unit tests for random option

### ISSUE THREAD

**Issue by strdr4605** [strdr4605/mockingcase#13]
Currently, there are no unit tests for option ` {random: true}`. Should discuss possible test checks for this option.

**Comment by emilioidk** [comment]
I guess the only sense there is in testing randoms is that

1. It does not raise an error
2. The result is equals to the input when compared in a case insensitive manner.

**Comment by strdr4605** [comment]
Package has one test
```js
test('Returned string should have same length as input string', () => {
    const input = 'hello world';
    const options = {
      random: true
    };
    expect(mOcKiNgCaSe(input)).toHaveLength(input.length);
    expect(mOcKiNgCaSe(input, options)).toHaveLength(input.length);
  });
```
I thought maybe about some *regex*!

**Comment by emilioidk** [comment]
I haven't found any specification but is the purpose of mockingcase to only modify casing or does some occasional replacement of characters occur? If it is only casing then I guess one can assure that passing the input and the result to the same casing (should work both with lower and upper case) would give equivalent values. I.e.

```javascript
    [...]
    expect(input.toLowerCase()).toBe(mOcKiNgCaSe(input).toLowerCase());
    [...]
```

**Comment by emurano** [comment]
You could also verify that at least some letters have their case changed

**Comment by avahe-kellenberger** [comment]
Due to the nature of randomness, there's a chance that the casing could be left untouched - I'm curious if this is a behavior @strdr4605 would want to change. 

I will clarify the documentation of `random` and write unit tests for the option, when/if we hear back from him.
