### ISSUE TITLE
Add firstUpper option

### ISSUE THREAD

**Issue by strdr4605** [strdr4605/mockingcase#19]
Currently, the package converts even positions of characters to lowercase and odd positions to uppercase. 
**firstUpper** options should reverse the converting pattern. 
Example: 
```javascript
const mOcKiNgCaSe = require('mockingcase');
mOcKiNgCaSe('example'); // eXaMpLe
mOcKiNgCaSe('example', {firstUpper: true}); //  ExAmPlE
```
if both **random** and **firstUpper** options are set to `true` first character should always be uppercase

**Comment by coreyladovsky** [comment]
I have just submitted a pull request for this issue.
