### ISSUE TITLE
Add option that removes all non letters characters before converting

### ISSUE THREAD

**Issue by strdr4605** [strdr4605/mockingcase#22]
```js
mOcKiNgCaSe('42foo!bar', {letters: true});
//=> 'fOoBaR'
mOcKiNgCaSe('foo bar 42', {letters: true});
//=> 'fOoBaR'
```

:heavy_exclamation_mark: **Maybe think about a better name for option**

**Comment by emurano** [comment]
Is A-Z and a-z sufficient for letters? Should I support other charsets?

Also, is `discardNonLetters` a better name for the option?

**Comment by strdr4605** [comment]
@emurano 
1. A-Z and a-z seems like a good beginning. Do you have other ideas?!
2.  `discardNonLetters` is a good name for a variable but is very long as an option name! 
Other possible names coming in mind:  
    - `onlyLetters`
    - `onlyAtoZ`
    - `aToZ`

**Comment by emurano** [comment]
@strdr4605 A-Za-z is fine with me :)

I'll go with onlyLetters.

**Comment by emurano** [comment]
Sorry for the delay. I'm not to contributing in github so I have to figure out what I need to do to push this to you.

**Comment by strdr4605** [comment]
1. You need to fork the repo
2. Clone forked repo on your machine
3. Create a branch like `only-letters`
4. Add the feature
5. Push to forked repo
6. Create a pull request from `emurano/mockingcase/only-letters` branch to `strdr4605/mockingcase/master` branch
