### ISSUE TITLE
Add functionality to override console.log

### ISSUE THREAD

**Issue by strdr4605** [strdr4605/mockingcase#36]
Would be nice to have a functionality that overrides all `console.log`s.
Example:
```js
mockingcase.overrideConsole();
console.log('Hello'); // hElLo
```

### TO DO:
1. Let the `overrideConsole` return the `mockingcase` object as `overrideString` so it can be used at importing like:
```js
const mOcKiNgCaSe = require('mockingcase').overrideConsole();
console.log('foobar')
// => 'fOoBaR'
mOcKiNgCaSe('foobar');
// => 'fOoBaR'
```
2. Add jsdoc and unit tests
3. Add `overrideConsole` in the `index.d.ts` file, so it can be used with typescript
4. Add **usage** in README after
```js
// Optionally create String.prototype.toMockingCase
mOcKiNgCaSe.overrideString();

'foo_bar'.toMockingCase();
//=> 'fOo_bAr'
```

**Comment by anmol5varma** [comment]
Can I pick this up?

**Comment by strdr4605** [comment]
@anmol5varma, as I see @Zohvek in https://github.com/Zohvek/mockingcase is working on this. Don't really know when he will make the pull request. I would like to wait for a week. If this issue will be available I will ping you! 😄

**Comment by Zohvek** [comment]
Sorry I got distracted with other stuff! PR coming soon.

**Comment by anmol5varma** [comment]
@strdr4605 I have implemented it. Just in case @Zohvek is busy with some stuff, I can raise a PR.

**Comment by strdr4605** [comment]
@anmol5varma, as there is a pull request for this issue, I would suggest helping this repo by review https://github.com/strdr4605/mockingcase/pull/47.

**Comment by strdr4605** [comment]
@anmol5varma, do you implemented all requirements from the **TO DO**? If yes you can also make a pull request for this issue!

**Comment by anmol5varma** [comment]
@strdr4605 I didn't implement 3,4. Will try to incorporate those too and raise a PR

**Comment by anmol5varma** [comment]
What do you mean by jsdoc?
