### ISSUE TITLE
Add option that converts only specific letters

### ISSUE THREAD

**Issue by strdr4605** [strdr4605/mockingcase#39]
Option object should have these fields:
`upper` should be of type `string` or  instanceof `RegExp` 
`lower` should be of type `string` or  instanceof `RegExp` 
else 
```js
throw TypeError(`options.upper: Expected string or RegExp but got "${typeof upper}"`);
```

The RegExp will be created as:
```js
if (options.upper) const upperRegExp = new RegExp(options.upper, 'gi');
if (options.lower) const lowerRegExp = new RegExp(options.lower, 'gi');
```
## Possible solution:
**Step 1:**
Convert the input with default behavior (even prostion: lowerCase; odd position: upperCase)
or if any option is present that do it first:
- remove non letters if `onlyLetters`
- odd prostion: lowerCase; even position: upperCase if `firstUpper`
- random case if `random`

**Step 2:**
```js
return step1Input
.replace(lowerRegExp, toLowerCase).
.replace(upperRegExp, toUpperCase);

```
**`upper` has a higher priority so convert letters that much that regex after conversion of `lower`**

### Expected:
```js
mockingcase("Hello World", { upper: "worl" });
// "hElLo WORLd"
mockingcase("Hello World", { upper: /worl/ });
// "hElLo WORLd"

mockingcase("Hello World", { upper: "[worl]" });
// "hELLO WORLd"
mockingcase("Hello World", { upper: /[worl]/ });
// "hELLO WORLd"

mockingcase("Hello World", { upper: /[worl]/, firstUpper: true });
// "HELLO WORLd"
```

### TO DO:

- [x] Add **upper** and **lower** options and implement them.
- [x] Comment options using jsdoc
- [x] Add unit test for **upper** and **lower** options
- [x] Add declaration of **upper** and **lower** options for Typescript, [Declaration Files](https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html)
- [x] Add usage and describe **upper** and **lower** options in README

### Status:
@cukejianya is working on this!

**Comment by cukejianya** [comment]
@strdr4605 Do you mind if I take this on?

**Comment by strdr4605** [comment]
@cukejianya, you can work on this. Let me know if you need some help!

**Comment by strdr4605** [comment]
@cukejianya, Wanted to ask your opinion about RexExp flags. 

For every letter in the string is needed to check
```js
letter.match(new RegExp(options.upper, 'g'))
```
`i` flag should be added along with `g` flag and then the regex will ignore case, so 
```js
new RegExp('a', 'gi')
```
will match for both `a` and `A`.

**Comment by strdr4605** [comment]
@cukejianya, As I discussed with some people, requirements for this issue will be probably changed! :blush: 

**Idea:** upper/lower should behave like `String.prototype.replace` after default convert

I will think again and change them in the next days. If you have some opinion, please write.

**Comment by cukejianya** [comment]
@strdr4605 When you say upper/lower should behave like `String.prototype.replace`, do you mean that `mockingcase("Hello World", upper:"worl")` should return `"Hello WORLd"` instead of `"heLLO WORld"`

**Comment by strdr4605** [comment]
@cukejianya, The new idea is: 
**step1**: default convert "hElLo wOrLd" 
**step2**: "hElLo wOrLd".replace(new RegExp(upper, 'gi'), toUpperCase)
**Use case**
```js
mockingcase("Hello World", { upper: "worl" });
// step1: "hElLo wOrLd"
// step2: "hElLo WORLd"
mockingcase("Hello World", { upper: /worl/ });
// step1: "hElLo wOrLd"
// step2: "hElLo WORLd"

mockingcase("Hello World", { upper: "[worl]" });
// step1: "hElLo wOrLd"
// step2: "hELLO WORLd"
mockingcase("Hello World", { upper: /[worl]/ });
// step1: "hElLo wOrLd"
// step2: "hELLO WORLd"
```
If other options are present the order should be:
1. onlyLetter: remove non letters
2. random: random case
3. lower: lower replace
4. upper: upper replace
5. firstUpper: Before returning make sure first character is converted to upperCase

**Comment by cukejianya** [comment]
Gotcha. So that means that I should ignore:

> 1. If only upper is present, then convert other letters that don't much the regex to lower case

> 2. If only lower is present, then convert other letters that don't much the regex to upper case

I should only convert letters that match regex. And for those that do not match, default to `convert(input, (str, i) => i % 2 === 1)`  (Unless other options are passed). Am I correct?

**Comment by strdr4605** [comment]
Yes, but I would suggest to first convert default or `random` or `firstUpper` and after go with `lower`/`upper`!
