### ISSUE TITLE
Add config for options on importing the package

### ISSUE THREAD

**Issue by strdr4605** [strdr4605/mockingcase#40]
Would be good to have a **config** function that can be used to create default options.
For example instead of:
```js
const mOcKiNgCaSe = require('mockingcase');
mOcKiNgCaSe('foo bar42', {onlyLetters: true, firstUpper: true});
//=> 'FoO BaR'

mOcKiNgCaSe('foo bar', {firstUpper: true});
//=> 'FoO BaR'
```
to have this possibility:
```js
const mOcKiNgCaSe = require('mockingcase').config({onlyLetters: true, firstUpper: true});
// const mOcKiNgCaSe = require('mockingcase');
// mOcKiNgCaSe.config({onlyLetters: true, firstUpper: true});

mOcKiNgCaSe('foo bar42');
//=> 'FoO BaR'

mOcKiNgCaSe('foo bar');
//=> 'FoO BaR'
```
and when including  options for a specific case, to override selected config options:
```js
const mOcKiNgCaSe = require('mockingcase').config({onlyLetters: true, firstUpper: true});
// const mOcKiNgCaSe = require('mockingcase');
// mOcKiNgCaSe.config({onlyLetters: true, firstUpper: true});

mOcKiNgCaSe('foo bar42');
//=> 'FoO BaR'

mOcKiNgCaSe('foo bar42', {onlyLetters: false, firstUpper: false});
//=> 'fOo bAr42'
```
**config** function should return modified mOcKiNgCaSe
### TO DO:

- [x] Add  **config** function and its implementation.
- [x] Comment it using jsdoc
- [x] Add 2-3 unit tests for this behavior
- [x] Add declaration of **config** function for Typescript, [Declaration Files](https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html)
- [x] Add usage and describe **config** function in README

**Comment by RicardoE105** [comment]
instead of something like this:

`const mOcKiNgCaSe = require('mockingcase').config({onlyLetters: true, firstUpper: true})`

would this work for you?

`const mOcKiNgCaSe = require('mockingcase')({ config: {onlyLetters: true, firstUpper: true} })`

**Comment by strdr4605** [comment]
@RicardoE105 , it is an interesting approach, but I think that is hard to implement (maybe impossible in this package) because when requiring a package it should return a working module, not a function that returns another function. 
Also, we can inspire from [dotenv](https://www.npmjs.com/package/dotenv) where they use 
```js
require('dotenv').config({ path: '/full/custom/path/to/your/env/vars' })
```
From my perspective approach above is more understandable to the developers comparing to your proposal. But I am open to discussions, and if you are really interested in this approach, I would suggest forking this repo and trying to implement for learning purpose. Or if you want to contribute to this package try to implement the approach described in the issue.
