### ISSUE TITLE
Fix package to work from CDN

### ISSUE THREAD

**Issue by strdr4605** [strdr4605/mockingcase#51]
This error is showing up when the package is used from [CDN](https://en.wikipedia.org/wiki/Content_delivery_network)
![image](https://user-images.githubusercontent.com/16056918/63636754-45c08500-c67c-11e9-8947-dd82d0576488.png)
Possible CDNs to work with:

| site | CDN |
| -- | -- |
| https://unpkg.com | https://unpkg.com/mockingcase@1.9.1/index.js |
| https://www.jsdelivr.com | https://cdn.jsdelivr.net/npm/mockingcase@1.9.1/index.min.js |

### DO TO:
- [x] Fix the error
- [x] Add tests
- [x] Add example of CDN usage in README

**Comment by maxrumsey** [comment]
We could just replace the last line of `index.js` with the following:
```
if (typeof module !== 'undefined') module.exports = mOcKiNgCaSe
```

**Comment by strdr4605** [comment]
@maxrumsey, You can take this issue if you want to contribute :blush:
