### ISSUE TITLE
Questions from maintainer

### ISSUE THREAD

**Issue by strdr4605** [strdr4605/mockingcase#52]
- [ ] 1. Should the `mOcKiNgCaSe` be exported as default?
- [x] 2. Should the `mOcKiNgCaSe` function be renamed in `mockingcase`?
- [x] 3. For consistency, should the [Definition file](https://github.com/strdr4605/mockingcase/blob/master/index.d.ts), [Main file](https://github.com/strdr4605/mockingcase/blob/master/index.js) and [Test file](https://github.com/strdr4605/mockingcase/blob/master/mockingcase.test.js) have all `index` or `mockingcase` name?

**Comment by distalx** [comment]
Hi @strdr4605,

> * Should the `mOcKiNgCaSe` be exported as default?

Yes. if that the only functionality you are exposing. 

> * Should the `mOcKiNgCaSe` function be renamed in `mockingcase`?

How about `MockingCase` instead.

> * For consistency, should the [Definition file](https://github.com/strdr4605/mockingcase/blob/master/index.d.ts), [Main file](https://github.com/strdr4605/mockingcase/blob/master/index.js) and [Test file](https://github.com/strdr4605/mockingcase/blob/master/mockingcase.test.js) have all `index` or `mockingcase` name?

It comes down to your personal preference. my personal preference and what I have observed from several project is as follow.

- type-definations are kept inside a `types` directory. 
- keep functionality  under `offering-package.js` and test under `offering-package.test.js`. import them to `index.js` and then expose that/those api(s).

**Comment by strdr4605** [comment]
@distalx thank you for feedback.
 
> type-definations are kept inside a `types` directory.

As the package is not big I don't want to have redundant folders.

One solution could be to move the main files to `src` folder

...
- `src`
  - `mockingcase.d.ts`
  - `mockingcase.js`
  - `mockingcase.test.js`

...

> How about `MockingCase` instead.

The name only affects how you call the function in the browser by CDN. `MockingCase` is a class name, so maybe better to stick with `mockingCase` or `mockingcase` as in first place it is a function ?!

**Comment by distalx** [comment]
In that case `mockingCase` or `mockingcase` both sounds good.

**Comment by strdr4605** [comment]
Closing as most of the questions resolved
