### ISSUE TITLE
Fix mOcKiNgCaSe.config overridedDefaultOptions?

### ISSUE THREAD

**Issue by strdr4605** [strdr4605/mockingcase#54]
At the moment overriding default options from `mOcKiNgCaSe.config`
```js
const options = overridedDefaultOptions || defaultOptions;
```
maybe is better to merge `defaultOptions` with `overridedDefaultOptions` and NOT just replace it?!

**Comment by thunderlorn** [comment]
Would this work for this?  Having trouble installing the package locally, sorry.

`const options = overridedDefaultOptions ? {...overridedDefaultOptions, ...defaultOptions} : defaultOptions`

**Comment by strdr4605** [comment]
@thunderlorn, if you want to test it locally, try:
```bash
cd mockingcase/
pwd
```
modify the mockingcase package
```bash
cd ../test-project
npm i --save path/to/mockingcase
```
test your modification. But also don't forget about unit tests

------------
Your ternary logic is a nice approach but
the `overridedDefaultOptions` should be the second argument as it should override previous values.

`{...overridedDefaultOptions}` is a new syntax which is not supported by node v6. At the moment `mockingcase` supports node v6 and higher.
Try using `Object.assign`

-----
You can work on this issue. Let me know if you need some help. :blush: 
Don't forget to rewrite tests for `mockingcase.config()`
