### ISSUE TITLE
Remove unnecessary links from table of contents

### ISSUE THREAD

**Issue by strdr4605** [strdr4605/mockingcase#61]
Having subsections links (Self Hosting, CDN Usage) in the table of contents for **Browser Usage** is not so important.

Better to remove them as **Browser Usage** is short enough to read every subsection.

**Comment by rubiin** [comment]
can i take this

**Comment by strdr4605** [comment]
@rubiin, yes.

**Comment by rubiin** [comment]
ok on it

**Comment by rubiin** [comment]
https://github.com/strdr4605/mockingcase/pull/62 here is a pr
