### ISSUE TITLE
Move main files to src folder

### ISSUE THREAD

**Issue by strdr4605** [strdr4605/mockingcase#65]
As the repo has a lot of files, it became a little messy. In discussion https://github.com/strdr4605/mockingcase/issues/52#issuecomment-537813367
I think is better to add an `src` folder with this structure

- `src`
  - `mockingcase.d.ts`
  - `mockingcase.js`
  - `mockingcase.test.js`

### TO DO:

- [ ] Create `src` folder
- [ ] Rename and move main files to `src` folder
- [ ] Update `package.json`
- [ ] Check that tests, pre-commit, prettier and eslint works properly
- [ ] Check that [Declaration Files](https://github.com/strdr4605/mockingcase/blob/master/index.d.ts) for Typescript works properly

**Comment by wale-bant** [comment]
Hi, can I work on this?

**Comment by strdr4605** [comment]
@wale-bant, yes. Let me know if you need some help!

**Comment by EnderDragonneau** [comment]
Oh, sorry, I already done the job... I am writting the PR message...

**Comment by wale-bant** [comment]
Ok Ender
