### ISSUE TITLE
Fix Browser Usage link in table of contents

### ISSUE THREAD

**Issue by strdr4605** [strdr4605/mockingcase#76]
When clicking on the **Browser Usage** from API table of contents it does not jump to the sections
 
A possible solution is to add a `a` tag like in this example
```md
- [mOcKiNgCaSe(input, [options]) ⇒ <code>string</code>](#mOcKiNgCaSe)
```

```html
<a name="mOcKiNgCaSe"></a>
```

**Comment by AndreyLop** [comment]
Fixed https://github.com/strdr4605/mockingcase/pull/77
