### ISSUE TITLE
Add templates for issues and pull requests

### ISSUE THREAD

**Issue by strdr4605** [strdr4605/mockingcase#79]
Useful links:
- https://help.github.com/en/articles/creating-issue-templates-for-your-repository
- https://help.github.com/en/articles/creating-a-pull-request-template-for-your-repository
- https://embeddedartistry.com/blog/2017/8/4/a-github-pull-request-template-for-your-projects

**Comment by maxrumsey** [comment]
I'd be able to take a stab at this! Any idea of what you want your templates to look like?

**Comment by strdr4605** [comment]
### Issue template

As this package is not so popular and it has no 🐞  😅 maybe a bug template is not a priority right now.
At the moment all issues are created by me and exposed to anyone who wants to contribute.
From my experience, every issue should be well described so any fresh contributor can easily understand what should be done.
Good examples are issues with a TODO section #40, #39 and others.
I really like #39 as it has:
1. Description (Motivation)
2. Possible solution (as a guide for noobie or suggestion)
3. Expected result
4. TODO (with 5 items in the checklist)

^ This is a good template to start from.

### Pull request template

I think [this example](https://github.com/embeddedartistry/templates/blob/master/oss_docs/PULL_REQUEST_TEMPLATE.md). is a good start. But **How Has This Been Tested?** is no needed in this case as for new features or fixes unit tests are required. 

---------------------

@maxrumsey, If I am not wrong if you create templates in your fork we can check how the work in your repo. Also, I am open to any suggestions so you can propose other changes.

**Comment by strdr4605** [comment]
@maxrumsey, do you still plan to work on this?
